display:
  mach: 3
  unit:
    name: "mph"
    factor: 2.23694
quarkus:
  http:
    port: 8080
  datasource:
    db-kind: mysql
    username: root
    password: 123456
    jdbc:
      url: jdbc:mysql://192.168.184.129:3308/quarkus_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      max-size: 8
      min-size: 2
    hibernate-orm:
      database:
        generation: drop-and-create
      log:
        sql: true
